### ISSUE TITLE
readme more appealing and easy for the new user.

### ISSUE THREAD

**Issue by Ayush-Tibrewal** [SidharthMudgil/mini-projects#11]
@SidharthMudgil  please assign me this issue under hackoctober fest

**Comment by SidharthMudgil** [comment]
How you plan to make current readme more appealing?

**Comment by Ayush-Tibrewal** [comment]
Here are some changes which we can do make make it more appealing and user friendly ( as 90 percent of the contributors are new to open source )
![Screenshot_2023-10-01-11-41-52-05_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/SidharthMudgil/mini-projects/assets/96817905/989a457c-7287-4b70-b6dd-d9f65ffe65a2)

![Screenshot_2023-10-01-11-41-55-41_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/SidharthMudgil/mini-projects/assets/96817905/ca0394c8-8997-4a95-b689-b6d81f45adb5)

![Screenshot_2023-10-01-11-42-00-74_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/SidharthMudgil/mini-projects/assets/96817905/20fb8519-bf91-4bd2-b92d-915e8dec577c)

**Comment by SidharthMudgil** [comment]
no, it is not required... If you want to work on documentation you have to update the documentation for the whole project.. readme for all subdirectories too

**Comment by SidharthMudgil** [comment]
#1 this is similar issue
