### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by SidharthMudgil** [SidharthMudgil/mini-projects#2]
I would like to request that the README file for the  repository should be improved to make it easier to navigate and understand. The current README file does not provide any information about the repository. It would be helpful to have a more comprehensive README file that provides a clear overview of the repository, including its purpose, How to navigate to for particular projects.

**Comment by aryangavit** [comment]
Hey can you assign me this issue

**Comment by SidharthMudgil** [comment]
@aryangavit Assigned it, Create a easy to navigate documentation...

**Comment by aryangavit** [comment]
Hi, regarding your "Feed App" project, can you give some brief points about it, I am not familiar with kotlin.

**Comment by SidharthMudgil** [comment]
It's a jetpack compose app that uses paging3 for showing infinite scrollable posts ...

Also, currently your documentation all apps are in single readme... Should it be like seperate readme for each folder or what?

For example clicking on Android projects should go to android/readme....

**Comment by aryangavit** [comment]
> It's a jetpack compose app that uses paging3 for showing infinite scrollable posts ...
> 
> Also, currently your documentation all apps are in single readme... Should it be like seperate readme for each folder or what?
> 
> For example clicking on Android projects should go to android/readme....

Yes, if you want a separate readme files for each android, flutter ,C++, Java, ML and scripts then I can do that. Then I'll create a table of contents on the main readme linked to subfolders readme.

**Comment by aryangavit** [comment]
> Hi, regarding your "Feed App" project, can you give some brief points about it, I am not familiar with kotlin.

Can you pls do the same for your "Memepur" app

**Comment by SidharthMudgil** [comment]
> > Hi, regarding your "Feed App" project, can you give some brief points about it, I am not familiar with kotlin.
> 
> Can you pls do the same for your "Memepur" app

App for showing jokes from different categories... user can also add new category and add jokes to existing categories

**Comment by SidharthMudgil** [comment]
> > It's a jetpack compose app that uses paging3 for showing infinite scrollable posts ...
> > Also, currently your documentation all apps are in single readme... Should it be like seperate readme for each folder or what?
> > For example clicking on Android projects should go to android/readme....
> 
> Yes, if you want a separate readme files for each android, flutter ,C++, Java, ML and scripts then I can do that. Then I'll create a table of contents on the main readme linked to subfolders readme.

That'll be great

**Comment by SidharthMudgil** [comment]
@aryangavit can you make all the projects in table in each type... like for android make it name(which is also link) | description and for main repo just something like below

# Repo name
description about repo

## Table of context
 - projects
 - how to contribute
 
in projects section add like
 - android
 - flutter
 
 and then they should open the respective readme and then for each also include similar for example:
 Android Projects
 small description
 
 table of context
 projects
 installation
 
 for android projects use https://github.com/SidharthMudgil/lg-motion [manual installation only]
simmilary for others

**Comment by aryangavit** [comment]
> @aryangavit can you make all the projects in table in each type... like for android make it name(which is also link) | description and for main repo just something like below
> # Repo name
> 
> description about repo
> ## Table of context
> 
>     * projects
> 
>     * how to contribute
> 
> 
> in projects section add like
> 
>     * android
> 
>     * flutter
> 
> 
> and then they should open the respective readme and then for each also include similar for example: Android Projects small description
> 
> table of context projects installation
> 
> for android projects use https://github.com/SidharthMudgil/lg-motion [manual installation only] simmilary for others

# mini-projects
desciption
# Table of contents
- [Projects](#projects)
- [How to Contribute](#how-to-contribute)
- [Installation](#installation)

## Projects
### [Android](./android/android_readme.md)
| Projects | Description |
| :---: | :--- | 
|[Basic Phrases](./android/BasicPhrases/)| This app allows users to learn basic phrases in different Indian Languages.|

### [Flutter](./flutter/flutter_readme.md)
| Projects | Description |
| :---: | :--- | 
|[Expense Tracker](./flutter/expense_tracker/)|Your classic expense tracker app with all the necessary features.|

## How to Contribute

## Installation


Did you mean something like this in the main README.md file? I don't know what to add in `How to Contribute` and `Installation` section, would it be okay if you fill that out, I'll create a template.

**Comment by SidharthMudgil** [comment]
Yes but in main readme only show the category, the installation part show in the specifically as you made in the table... with category as heading, then description than all projects and the installation part

**Comment by aryangavit** [comment]
> Yes but in main readme only show the category, the installation part show in the specifically as you made in the table... with category as heading, then description than all projects and the installation part 

Sorry but I'm not getting what you want, can you create a small template of it in markdown, so that I can understand it better.

**Comment by SidharthMudgil** [comment]
In man readme

# Mini Projects
About the project....

## Table of Content
- Projects
- Contribution

## Projects
- Android
- Flutter
- ....
## Contribution
.....


In Android readme
# Android Mini Projects
Summary....

## Table of Content
- Projects
- Installation

## Projects
| name + link | summary |
_____

## Installation
....
