### ISSUE TITLE
Add a project in C++

### ISSUE THREAD

**Issue by MahajanPreksha** [SidharthMudgil/mini-projects#20]
Hello, I want to add my project titled 'Supermarket Billing System'.
Please assign me this issue.
Thank you.

**Comment by SidharthMudgil** [comment]
Go On, I have assigned you the issue, please follow the guidelines

**Comment by SidharthMudgil** [comment]
follow proper contribution guidelines.. update readme.

**Comment by MahajanPreksha** [comment]
Updated readme.md file.

**Comment by MahajanPreksha** [comment]
Please add the required label of hacktoberfest-accepted.
Thank you

**Comment by SidharthMudgil** [comment]
It is not required.

**Comment by SidharthMudgil** [comment]
YOUR PR/MRS MUST BE IN A REPO TAGGED WITH THE “HACKTOBERFEST” TOPIC, OR HAVE THE “HACKTOBERFEST-ACCEPTED” LABEL.
