### ISSUE TITLE
Add Following ML projects

### ISSUE THREAD

**Issue by newtoallofthis123** [SidharthMudgil/mini-projects#5]
Hey! Really liked some of the projects in the `/ml` folder and since I am learning ML myself, I would like to contribute some of my own projects to the repo. Here are some that I would like to add

- Insurance Prediction
- Cats vs Dogs Recognition
- Iris Data Analysis
- Letter Recognition

I couldn't find any Contribution.md, so I just wanted to confirm first. Also, can I be assigned this issue for hacktoberfest?

**Comment by SidharthMudgil** [comment]
Yeah, Go on just make sure you add the projects in the readme file also... and I have already marked the repo as hacktoberfest isn't it sufficient?

**Comment by newtoallofthis123** [comment]
Oh sorry, I didn't see the `hacktoberfest` label. That would suffice and yes I'll add my projects to the readme file.

Thanks

**Comment by SidharthMudgil** [comment]
Are you working on the issue? I've assigned it to you

**Comment by newtoallofthis123** [comment]
Thanks! I am working on it. Will open the pr at the latest

**Comment by Riyagupta0204** [comment]
I have recently started working on ML.I really wish to contribute my own projects.
Multiple disease Prediction system
@SidharthMudgil

**Comment by SidharthMudgil** [comment]
@Riyagupta0204 yeah why not go ahead.... I'll love to accept it.

**Comment by SidharthMudgil** [comment]
@newtoallofthis123 @Riyagupta0204 please don't use fixes and other words so that it will not close issue automatically. 

Also @newtoallofthis123 if you like to add contribution md create a new issue I'll accept that  just add guidelines accordingly.

**Comment by newtoallofthis123** [comment]
Sure! I just finished adding this cool dogs vs cat project 😄

**Comment by SidharthMudgil** [comment]
Awesome. Keep working hard 💪
