### ISSUE TITLE
Add CPP problems/projects

### ISSUE THREAD

**Issue by JenilGajjar20** [SidharthMudgil/mini-projects#6]
Hey, @SidharthMudgil. 

I would like to contribute to the repository as a part of **hacktorberfest**. I want to contribute some of my **C++** projects. 

Can u please assign me the task?

**Comment by SidharthMudgil** [comment]
Yeah go ahead, follow contribution guidelines

**Comment by RotenKiwi** [comment]
Hello @SidharthMudgil , would like to contribute a small project in cpp as a part of Hacktoberfest. Kindly assign the task.

**Comment by SidharthMudgil** [comment]
Yeah Make sure you don't add same projects  as @JenilGajjar20 also add installation guide, input, output for this project.

**Comment by SidharthMudgil** [comment]
@aryangavit Please don't spam pull requests they are mini projects both can be added in single pull request.

**Comment by aryangavit** [comment]
> @aryangavit Please don't spam pull requests they are mini projects both can be added in single pull request.

Hey @SidharthMudgil , I think you mistakenly tagged me. I haven't made any pull requests since last week.

**Comment by SidharthMudgil** [comment]
@aryangavit sorry, my mistake.
