### ISSUE TITLE
Add SpringBoot Java Fullstack projects

### ISSUE THREAD

**Issue by TharunBalaji2004** [SidharthMudgil/mini-projects#9]
Hey there @SidharthMudgil, I would like to contribute Fullstack Java projects - Student, Employee Management System as part of Hacktoberfest 2023. Can you assign me this task ? 😊

Involves RESTful Architecture and DB connection

**Comment by SidharthMudgil** [comment]
Yeah Go On, I'll assign the issue to you. Remember to follow contribution guidelines and project naming convention. Also add installation guide, input, output.

**Comment by TharunBalaji2004** [comment]
Alright sure!
